# Stage 1: Build React App
FROM node:18 as build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Stage 2: Nginx Configuration
FROM nginx:alpine
WORKDIR /usr/share/nginx/html
COPY --from=build-stage /app/build/ .
EXPOSE 81
CMD ["nginx", "-g", "daemon off;"]
