spring.application.name=Paperless_components
server.port=8081

spring.docker.compose.enabled=false

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=rabbitmqadmin
spring.rabbitmq.password=rabbitmqadmin
