version: '3.8'

services:
  api:
    build:
      context: ..
      dockerfile: Dockerfiles/Dockerfile-API
    container_name: rest-api
    ports:
      - "8081:8081"
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - shared-pdfs:/app/pdfs

  frontend:
    build:
      context: ..
      dockerfile: Dockerfiles/Dockerfile-Frontend
    container_name: frontend
    ports:
      - "81:81"
    networks:
      - app-network

  postgres:
    build:
      context: ..
      dockerfile: Dockerfiles/Dockerfile-DB
    container_name: Datenbank
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmqadmin
      RABBITMQ_DEFAULT_PASS: rabbitmqadmin
    networks:
      - app-network

  tesseract-ocr:
    build:
      context: ..
      dockerfile: Dockerfiles/Dockerfile-Tesseract-OCR
    container_name: tesseract-ocr
    volumes:
      - shared-pdfs:/app/pdfs
    networks:
      - app-network
    environment:
      RABBITMQ_HOST: rabbitmq      # DNS-Name vom RabbitMQ-Service
      RABBITMQ_USER: rabbitmqadmin
      RABBITMQ_PASS: rabbitmqadmin
    depends_on:
      - rabbitmq

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9090"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    #mem_limit: 1g
    ports:
      - "9200:9200"  # Elasticsearch API
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - app-network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.10
    container_name: kibana
    ports:
      - "5601:5601"  # Kibana Web Interface
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  shared-pdfs:
    driver: local
    driver_opts:
      o: bind
      device: ../PDFs
      type: none
  es_data:
    driver: local
  minio_data:
      driver: local
