# Stage 1: Build React App
FROM node:18 as build-stage
WORKDIR /app
COPY /src/frontend/package*.json .
RUN npm install
COPY ../src/frontend .
RUN npm run build

#Stage 2: Nginx Configuration
FROM nginx:alpine
WORKDIR /usr/share/nginx/html
RUN rm -rf /usr/share/nginx/html/*
COPY --from=build-stage /app/build/ .
COPY ../src/frontend/nginx.conf /etc/nginx/nginx.conf
EXPOSE 81
CMD ["nginx", "-g", "daemon off;"]
