FROM python:3.9-slim

RUN apt-get update && apt-get install -y \
    curl \
    && apt-get clean

COPY requirements.txt /app/requirements.txt
WORKDIR /app

RUN pip install --no-cache-dir -r requirements.txt

COPY . /app
CMD ["python", "main.py"]
