FROM maven:3.8.4-openjdk-17 AS build
WORKDIR /app
COPY ../pom.xml /app/
RUN mvn dependency:go-offline -B

COPY ../src /app/src
RUN mvn clean package -DskipTests

FROM openjdk:17-jdk-alpine AS runtime
WORKDIR /app
COPY --from=build /app/target/Paperless_components-0.0.1-SNAPSHOT.jar /app/paperless.jar
ENTRYPOINT ["java", "-jar", "/app/paperless.jar"]

