FROM python:3.9-slim

RUN apt-get update && apt-get install -y \
    tesseract-ocr \
    libtesseract-dev \
    poppler-utils \
    && apt-get clean

COPY src/main/resources/requirements-python.txt /app/requirements-python.txt
WORKDIR /app
RUN pip install --no-cache-dir -r /app/requirements-python.txt

COPY src/OCR /app

CMD ["python", "main.py"]
